services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
    networks:
      - app-net

  backend:
    build:
      context: ./backend/project
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    command: npm start
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/tmp:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

networks:
  app-net:
