version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
    networks:
      - app-net

  backend:
    container_name: backend
    build:
      context: ./backend/project
    ports:
      - '3001:3001' # Optional; remove if only accessed through nginx
    environment:
      - NODE_ENV=production
    command: npm start

    volumes:
      - ./backend/project/assets/images:/app/assets/images

    networks:
      - app-net

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

networks:
  app-net:
